baseurl = "https://antjowie.github.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Angelo's Portfolio"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
# pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "angelos-portfolio"
# googleAnalytics = "UA-120723585-1"

publishDir = "../"
taskLists = "true"

[Params]
  homeTitle = "Welcome to my portfolio" # Set a different text for the header on the home page
  subtitle = "A place that contains all I have created"
  logo = "img/icons/site-icon.png"
  favicon = "img/icons/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
 gcse = "001716844541583678590:jrms-ixh6ca" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

# [[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Angelo Anthony Rettob"
  website = "https://antjowie.github.io/"
  email = "angelo05rettob@gmail.com"
#   facebook = "username"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "antjowie"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4
